[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor = "6cQ5c4CQKfME2CC4GNuNxmsJWe3k4ki5j2VrsNSEzuSd"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
